-- ---------------------------------------------------
-- CRIAÇÃO DAS TABELAS
-- ---------------------------------------------------

CREATE TABLE IF NOT EXISTS tb_usuario (
	id_usuario UUID,
	nome VARCHAR(120) NOT NULL,
	email VARCHAR(150) NOT NULL UNIQUE,
	senha_hash VARCHAR(255) NOT NULL,
	cargo VARCHAR(80),
	id_cozinha INTEGER,
	id_perfil INTEGER NOT NULL,
	ativo BOOLEAN NOT NULL DEFAULT true,
	ultimo_login TIMESTAMP,
	criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_usuario)
);

CREATE TABLE IF NOT EXISTS tb_perfil (
	id_perfil INTEGER GENERATED BY DEFAULT AS IDENTITY,
	tipo_acesso VARCHAR(50) NOT NULL UNIQUE,
	descricao VARCHAR(255),
	PRIMARY KEY (id_perfil)
);

CREATE TABLE IF NOT EXISTS tb_cozinha (
	id_cozinha INTEGER GENERATED BY DEFAULT AS IDENTITY,
	nome VARCHAR(120) NOT NULL,
	codigo VARCHAR(20) NOT NULL UNIQUE,
	endereco VARCHAR(255),
	ativo BOOLEAN NOT NULL DEFAULT true,
	criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_cozinha)
);

CREATE TABLE IF NOT EXISTS tb_produto (
	id_produto INTEGER GENERATED BY DEFAULT AS IDENTITY,
	nome VARCHAR(150) NOT NULL,
	marca VARCHAR(80),
	id_categoria INTEGER,
	id_unidade INTEGER NOT NULL,
	codigo_barras VARCHAR(50) UNIQUE,
	foto_url VARCHAR(255),
	ativo BOOLEAN NOT NULL DEFAULT true,
	criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_produto)
);

CREATE TABLE IF NOT EXISTS tb_categoria (
	id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY,
	nome VARCHAR(80) NOT NULL UNIQUE,
	descricao VARCHAR(255),
	PRIMARY KEY (id_categoria)
);

CREATE TABLE IF NOT EXISTS tb_unidade_medida (
	id_unidade INTEGER GENERATED BY DEFAULT AS IDENTITY,
	sigla VARCHAR(10) NOT NULL UNIQUE,
	descricao VARCHAR(60) NOT NULL,
	PRIMARY KEY (id_unidade)
);

CREATE TABLE IF NOT EXISTS tb_produto_fornecedor (
	id_produto INTEGER NOT NULL,
	id_fornecedor INTEGER NOT NULL,
	codigo_no_fornecedor VARCHAR(50),
	preco_referencia DECIMAL(12,2),
	lead_time_dias INTEGER,
	PRIMARY KEY (id_produto, id_fornecedor)
);

CREATE TABLE IF NOT EXISTS tb_fornecedor (
	id_fornecedor INTEGER GENERATED BY DEFAULT AS IDENTITY,
	nome_juridico VARCHAR(150) NOT NULL,
	cnpj VARCHAR(18) NOT NULL UNIQUE,
	email VARCHAR(150),
	whatsapp VARCHAR(20),
	nota_avaliacao INTEGER,
	ativo BOOLEAN NOT NULL DEFAULT true,
	criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_fornecedor)
);

CREATE TABLE IF NOT EXISTS tb_produto_parametro_cozinha (
	id_produto INTEGER NOT NULL,
	id_cozinha INTEGER NOT NULL,
	estoque_minimo DECIMAL(12,3) NOT NULL DEFAULT 0,
	estoque_maximo DECIMAL(12,3),
	consumo_medio_dia DECIMAL(12,3),
	PRIMARY KEY (id_produto, id_cozinha)
);

CREATE TABLE IF NOT EXISTS tb_estoque_lote (
	id_lote INTEGER GENERATED BY DEFAULT AS IDENTITY,
	id_produto INTEGER NOT NULL,
	id_cozinha INTEGER NOT NULL,
	id_fornecedor INTEGER,
	numero_lote VARCHAR(50) NOT NULL,
	numero_nota_fiscal VARCHAR(50),
	qtd_inicial DECIMAL(12,3) NOT NULL,
	qtd_atual DECIMAL(12,3) NOT NULL,
	data_entrada DATE NOT NULL,
	data_validade DATE,
	preco_unitario DECIMAL(12,2),
	status VARCHAR(20) NOT NULL DEFAULT 'ATIVO',
	PRIMARY KEY (id_lote)
);

CREATE TABLE IF NOT EXISTS tb_requisicao (
	id_requisicao INTEGER GENERATED BY DEFAULT AS IDENTITY,
	tipo_requisicao VARCHAR(20) NOT NULL,
	origem VARCHAR(20) NOT NULL,
	status VARCHAR(20) NOT NULL DEFAULT 'EM_ANALISE',
	motivo VARCHAR(255),
	id_cozinha INTEGER NOT NULL,
	id_usuario_requisicao UUID NOT NULL,
	id_usuario_aprovador UUID,
	data_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	data_aprovacao TIMESTAMP,
	PRIMARY KEY (id_requisicao)
);

CREATE TABLE IF NOT EXISTS tb_requisicao_item (
	id_requisicao_item INTEGER GENERATED BY DEFAULT AS IDENTITY,
	id_requisicao INTEGER NOT NULL,
	id_produto INTEGER NOT NULL,
	id_fornecedor_sugerido INTEGER,
	quantidade DECIMAL(12,3) NOT NULL,
	preco_estimado DECIMAL(12,2),
	observacao VARCHAR(255),
	PRIMARY KEY (id_requisicao_item)
);

CREATE TABLE IF NOT EXISTS tb_inventario (
	id_inventario INTEGER GENERATED BY DEFAULT AS IDENTITY,
	id_cozinha INTEGER NOT NULL,
	id_usuario_responsavel UUID NOT NULL,
	data_inicio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	data_fechamento TIMESTAMP,
	status VARCHAR(20) NOT NULL DEFAULT 'ABERTO',
	observacao VARCHAR(255),
	PRIMARY KEY (id_inventario)
);

CREATE TABLE IF NOT EXISTS tb_inventario_contagem (
	id_contagem INTEGER GENERATED BY DEFAULT AS IDENTITY,
	id_inventario INTEGER NOT NULL,
	id_lote INTEGER NOT NULL,
	qtd_registrada DECIMAL(12,3) NOT NULL,
	qtd_fisica DECIMAL(12,3) NOT NULL,
	divergencia DECIMAL(12,3),
	observacao VARCHAR(255),
	PRIMARY KEY (id_contagem)
);

CREATE TABLE IF NOT EXISTS tb_alerta (
	id_alerta INTEGER GENERATED BY DEFAULT AS IDENTITY,
	tipo VARCHAR(30) NOT NULL,
	severidade VARCHAR(10) NOT NULL,
	id_lote INTEGER,
	id_produto INTEGER,
	id_cozinha INTEGER NOT NULL,
	mensagem VARCHAR(255) NOT NULL,
	lido BOOLEAN NOT NULL DEFAULT false,
	criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id_alerta)
);